In [1]:
catalog = "spotify_etl"
layer = "bronze"
name_table = "bronze_play_history"

In [2]:
spark.sql(f"""
    CREATE TABLE IF NOT EXISTS {catalog}.{layer}.{name_table} (
        played_at STRING,
        track_id STRING,
        track_name STRING,
        artist_id STRING,
        artist_name STRING,
        album_id STRING,
        album_name STRING,
        context_type STRING,
        duration_ms BIGINT,
        processing_date DATE
    )
    USING DELTA
    PARTITIONED BY (processing_date)
    TBLPROPERTIES (
        delta.enableChangeDataFeed = true
    )
""")

DataFrame[]

In [3]:
%sql
SELECT * FROM spotify_etl.bronze.bronze_play_history

DataFrame[played_at: string, track_id: string, track_name: string, artist_id: string, artist_name: string, album_id: string, album_name: string, context_type: string, duration_ms: bigint, processing_date: date]